[build]
  base = "."
  publish = "ubuntu/command-x-frontend/dist"
  command = "cd ubuntu/command-x-frontend && npm install --legacy-peer-deps && npm run build:no-typecheck"

[build.environment]
  NODE_VERSION = "18"
  # Updated to force new deployment with latest fixes

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Handle asset paths
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
