/**
 * Direct Report Generator Utility
 *
 * This utility generates a report by opening a template HTML file and populating it with data
 */

import { WorkOrderData } from "@/components/accounting/WorkOrderStatusTable";

// Function to create HTML content for the report
const createReportHTML = (workOrders: WorkOrderData[]): string => {
  // Calculate totals
  const totalSWO = workOrders.reduce((sum, item) => sum + item.swoTotal, 0);
  const totalWOAmount = workOrders.reduce(
    (sum, item) => sum + item.woAmount,
    0
  );
  const totalRetainage = workOrders.reduce(
    (sum, item) => sum + item.retainageAmount,
    0
  );
  const totalDue = workOrders.reduce((sum, item) => sum + item.woDueAmount, 0);

  // Create table rows
  const tableRows = workOrders
    .map(
      (wo) => `
    <tr>
      <td>${wo.id}</td>
      <td>$${wo.swoTotal.toFixed(2)}</td>
      <td>$${wo.woAmount.toFixed(2)}</td>
      <td>$${wo.retainageAmount.toFixed(2)}</td>
      <td>${wo.dueDate}</td>
      <td>${wo.crewName || "Not Assigned"}</td>
    </tr>
  `
    )
    .join("");

  // Create the HTML content
  return `<!DOCTYPE html>
<html>
<head>
  <title>Financial Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 40px;
      color: #333;
    }
    h1, h2, h3 {
      color: #1a56db;
    }
    .header {
      text-align: center;
      margin-bottom: 30px;
    }
    .date {
      margin-bottom: 20px;
      color: #666;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 30px;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 12px;
      text-align: left;
    }
    th {
      background-color: #f8fafc;
      font-weight: bold;
    }
    tr:nth-child(even) {
      background-color: #f9fafb;
    }
    .summary {
      margin-top: 30px;
      border-top: 2px solid #ddd;
      padding-top: 20px;
    }
    .summary-item {
      display: flex;
      justify-content: space-between;
      margin-bottom: 10px;
    }
    .summary-label {
      font-weight: bold;
    }
    .footer {
      margin-top: 50px;
      text-align: center;
      color: #666;
      font-size: 12px;
    }
    .print-button {
      position: fixed;
      top: 20px;
      right: 20px;
      padding: 10px 20px;
      background-color: #1a56db;
      color: white;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
  </style>
</head>
<body>
  <button class="print-button" onclick="window.print()">Print Report</button>

  <div class="header">
    <h1>Command X Financial Report</h1>
    <div>Command X Construction</div>
    <div class="date">Generated on: ${new Date().toLocaleDateString()}</div>
  </div>

  <h2>Financial Summary</h2>
  <div class="summary">
    <div class="summary-item">
      <span class="summary-label">Total SWO Amount:</span>
      <span>$${totalSWO.toFixed(2)}</span>
    </div>
    <div class="summary-item">
      <span class="summary-label">Total W.O. Amount:</span>
      <span>$${totalWOAmount.toFixed(2)}</span>
    </div>
    <div class="summary-item">
      <span class="summary-label">Total Retainage:</span>
      <span>$${totalRetainage.toFixed(2)}</span>
    </div>
    <div class="summary-item">
      <span class="summary-label">Total Amount Due:</span>
      <span>$${totalDue.toFixed(2)}</span>
    </div>
  </div>

  <h2>Work Order Details</h2>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>SWO Total</th>
        <th>W.O. Amount</th>
        <th>Retainage</th>
        <th>Due Date</th>
        <th>Crew</th>
      </tr>
    </thead>
    <tbody>
      ${tableRows}
    </tbody>
  </table>

  <div class="footer">
    <p>This report was generated by Command X Construction Management System.</p>
    <p>© ${new Date().getFullYear()} Command X Construction. All rights reserved.</p>
  </div>
</body>
</html>`;
};

/**
 * Generate a financial report by opening it in a new window
 * @param workOrders - Array of work order data
 * @returns Window | null - The window object or null if blocked
 */
export const generateDirectReport = (
  workOrders: WorkOrderData[]
): Window | null => {
  try {
    // Generate the HTML content
    const htmlContent = createReportHTML(workOrders);

    // Open in a new window
    const reportWindow = window.open("", "_blank");

    if (!reportWindow) {
      return null;
    }

    // Write the content to the new window
    reportWindow.document.write(htmlContent);
    reportWindow.document.close();

    return reportWindow;
  } catch (error) {
    console.error("Error generating report:", error);
    return null;
  }
};

/**
 * Download the financial report as an HTML file
 * @param workOrders - Array of work order data
 */
export const downloadReport = (workOrders: WorkOrderData[]): void => {
  try {
    // Generate the HTML content
    const htmlContent = createReportHTML(workOrders);

    // Create a data URL
    const dataUrl = `data:text/html;charset=utf-8,${encodeURIComponent(
      htmlContent
    )}`;

    // Create a download link
    const link = document.createElement("a");
    link.href = dataUrl;
    link.setAttribute("download", "financial_report.html");
    document.body.appendChild(link);

    // Trigger download
    link.click();

    // Clean up
    document.body.removeChild(link);
  } catch (error) {
    console.error("Error downloading report:", error);
    throw error;
  }
};
