/**
 * Simple Report Generator Utility
 * 
 * This utility provides a basic report generator that doesn't rely on external libraries
 */

import { WorkOrderData } from "@/components/accounting/WorkOrderStatusTable";

/**
 * Generate a simple financial report for work orders
 * @param workOrders - Array of work order data
 * @param title - Report title
 * @param subtitle - Report subtitle
 * @returns A data URL for the generated report
 */
export const generateSimpleReport = (
  workOrders: WorkOrderData[],
  title: string = "Financial Report",
  subtitle: string = "Command X Construction"
): string => {
  // Calculate totals for the report
  const totalSWO = workOrders.reduce((sum, item) => sum + item.swoTotal, 0);
  const totalRetainage = workOrders.reduce((sum, item) => sum + item.retainageAmount, 0);
  const totalWOAmount = workOrders.reduce((sum, item) => sum + item.woAmount, 0);
  const totalDue = workOrders.reduce((sum, item) => sum + item.woDueAmount, 0);
  
  // Format date for the report
  const reportDate = new Date().toLocaleDateString();
  
  // Create HTML content for the report
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 40px;
          color: #333;
        }
        h1, h2, h3 {
          color: #1a56db;
        }
        .header {
          text-align: center;
          margin-bottom: 30px;
        }
        .date {
          margin-bottom: 20px;
          color: #666;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 30px;
        }
        th, td {
          border: 1px solid #ddd;
          padding: 12px;
          text-align: left;
        }
        th {
          background-color: #f8fafc;
          font-weight: bold;
        }
        tr:nth-child(even) {
          background-color: #f9fafb;
        }
        .summary {
          margin-top: 30px;
          border-top: 2px solid #ddd;
          padding-top: 20px;
        }
        .summary-item {
          display: flex;
          justify-content: space-between;
          margin-bottom: 10px;
        }
        .summary-label {
          font-weight: bold;
        }
        .footer {
          margin-top: 50px;
          text-align: center;
          color: #666;
          font-size: 12px;
        }
        .print-button {
          position: fixed;
          top: 20px;
          right: 20px;
          padding: 10px 20px;
          background-color: #1a56db;
          color: white;
          border: none;
          border-radius: 4px;
          cursor: pointer;
        }
      </style>
    </head>
    <body>
      <button class="print-button" onclick="window.print()">Print Report</button>
      
      <div class="header">
        <h1>${title}</h1>
        <div>${subtitle}</div>
        <div class="date">Generated on: ${reportDate}</div>
      </div>
      
      <h2>Financial Summary</h2>
      <div class="summary">
        <div class="summary-item">
          <span class="summary-label">Total SWO Amount:</span>
          <span>$${totalSWO.toFixed(2)}</span>
        </div>
        <div class="summary-item">
          <span class="summary-label">Total W.O. Amount:</span>
          <span>$${totalWOAmount.toFixed(2)}</span>
        </div>
        <div class="summary-item">
          <span class="summary-label">Total Retainage:</span>
          <span>$${totalRetainage.toFixed(2)}</span>
        </div>
        <div class="summary-item">
          <span class="summary-label">Total Amount Due:</span>
          <span>$${totalDue.toFixed(2)}</span>
        </div>
      </div>
      
      <h2>Work Order Details</h2>
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>SWO Total</th>
            <th>W.O. Amount</th>
            <th>Retainage</th>
            <th>Due Date</th>
            <th>Crew</th>
          </tr>
        </thead>
        <tbody>
          ${workOrders.map(wo => `
            <tr>
              <td>${wo.id}</td>
              <td>$${wo.swoTotal.toFixed(2)}</td>
              <td>$${wo.woAmount.toFixed(2)}</td>
              <td>$${wo.retainageAmount.toFixed(2)}</td>
              <td>${wo.dueDate}</td>
              <td>${wo.crewName || 'Not Assigned'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
      
      <div class="footer">
        <p>This report was generated by Command X Construction Management System.</p>
        <p>© ${new Date().getFullYear()} Command X Construction. All rights reserved.</p>
      </div>
    </body>
    </html>
  `;
  
  // Convert HTML to a data URL
  const dataUrl = `data:text/html;charset=utf-8,${encodeURIComponent(htmlContent)}`;
  
  return dataUrl;
};
