[build]
  base = "."
  publish = "dist"
  command = "pnpm install --no-frozen-lockfile && CI=false pnpm run build:no-typecheck"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
